// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-uneskuVm_5hGQP0QC6nCpFJ5z1P_rw',
    appId: '1:469115352408:web:a87a04c8f6db654751612d',
    messagingSenderId: '469115352408',
    projectId: 'melodaiapp',
    authDomain: 'melodaiapp.firebaseapp.com',
    storageBucket: 'melodaiapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEY5esa-4_FcQlCgdnrP6DlPLHiNjotfU',
    appId: '1:469115352408:android:e87db5504c5d1d5751612d',
    messagingSenderId: '469115352408',
    projectId: 'melodaiapp',
    storageBucket: 'melodaiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvAYERVISm_ty1YSmEG9pZooKD83o8VQQ',
    appId: '1:469115352408:ios:b2ff102b798264e651612d',
    messagingSenderId: '469115352408',
    projectId: 'melodaiapp',
    storageBucket: 'melodaiapp.firebasestorage.app',
    iosBundleId: 'com.melodai.melodaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvAYERVISm_ty1YSmEG9pZooKD83o8VQQ',
    appId: '1:469115352408:ios:b2ff102b798264e651612d',
    messagingSenderId: '469115352408',
    projectId: 'melodaiapp',
    storageBucket: 'melodaiapp.firebasestorage.app',
    iosBundleId: 'com.melodai.melodaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX-uneskuVm_5hGQP0QC6nCpFJ5z1P_rw',
    appId: '1:469115352408:web:a2387e6842105e5051612d',
    messagingSenderId: '469115352408',
    projectId: 'melodaiapp',
    authDomain: 'melodaiapp.firebaseapp.com',
    storageBucket: 'melodaiapp.firebasestorage.app',
  );
}
